#!/usr/bin/env bash
# script that pings an IP address passed as an argument

IP_address="$1"

fn=$(basename "${BASH_SOURCE[@]}")

if ! [ "$IP_address" ]; then
	echo "Usage: ${fn} {IP_ADDRESS}"
else
	ping -c 5 "${IP_address}"
fi
