#!/usr/bin/env bash
# This script displays a list of currently running processes.
# It must show all processes, for all users, including those which might not have a TTY
# It display in a user-oriented format
# It Shows process hierarchy

ps -auxf
